### ISSUE TITLE
Is there a way to trigger an automation on the esp8266 use a card number? I would like a fail back way to trigger onboard autionation if wifi goes out. 

### ISSUE THREAD

**Issue by towerclimber87** [avwuff/esphome-wiegand#2]

**Comment by avwuff** [comment]
Yup, you can just add code to the on_value to run a lambda to compare the card number and trigger the door.

**Comment by towerclimber87** [comment]
Would it be possible to provide an example?

**Comment by avwuff** [comment]
Sorry, ESPHome isn't really something i'm an expert in -- I would ask over there!

Cheers,
-av

**Comment by towerclimber87** [comment]
avwuff, I am hoping that you can help me out here as I have hit a wall. I
am unable to get the keypad to group kep press together. I need to be able
to press four keys and then enter to have it push out a code. currently it
reports every key press as a single key press.  It appears that you might
have been trying to do this with we have a key code?

        void update() override {
            // See if we have a valid code
            noInterrupts();
            bool rc = DoWiegandConversion();
            interrupts();

            if(rc) {
                lastCode = millis();
            } else {
                if(keyCodes.length() > 0) {
                    // We have a keyCode, see if the interdigit timer
expired
                    if(millis() - lastCode > 2000) {
                        // The interdigit timer expired, send the code and
reset for the next string
                        json_message(keyCodes);
                        keyCodes = "";
                    }
                }
            }
        }

**Comment by avwuff** [comment]
Actually, I didn't write my code to support keypads at all -- I'm kinda surprised you are even getting anything.  
This was written for RFID keycards to be scanned!

**Comment by towerclimber87** [comment]
I assume you are not interested at all in getting the keypad to work?

**Comment by avwuff** [comment]
I don't have one to test with and don't need it in my use case... keep in mind, all I did here was take someone else's Wiegand reader module code and marry it so it would work with ESPHome.
